### ISSUE TITLE
'test' set is not provided

### ISSUE THREAD

**Issue by zhanghang1989** [ccvl/detail-api#2]
Calling the API 'test' set, the image name is out of VOC2010 dataset.
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/data/VOCdevkit/VOC2010/JPEGImages/2008_000001.jpg'
```

**Comment by matthew-richard** [comment]
Version 4.0 made some updates to ```download.py``` that causes ```download.py pascal /your/directory``` to also download the test data. Could you re-run that command? (I will add a notice about this to the website)

**Comment by zhanghang1989** [comment]
Thanks! When I am running the command `python3 download.py pascal ~/data/`, I got the following error from my browser:
```
This site can’t be reached

host.robots.ox.ac.uk refused to connect.
Search Google for host robots 8080 eval downloads VOC 2010 test tar
ERR_CONNECTION_REFUSED
```

**Comment by matthew-richard** [comment]
If you paste http://host.robots.ox.ac.uk/ into your browser, do you get 
a connection refused error?

I get a regular site:

Are you accessing the internet from behind a firewall? If so, is VPN an 
option?

--Matt

**Comment by zhanghang1989** [comment]
The url http://host.robots.ox.ac.uk/ works for me. It is Pascal VOC website. But I still have the same error to download the dataset. I will try again using another machine. thanks

**Comment by matthew-richard** [comment]
What about http://host.robots.ox.ac.uk:8080 
<http://host.robots.ox.ac.uk:8080/>?

**Comment by zhanghang1989** [comment]
visiting http://host.robots.ox.ac.uk:8080 gives me the same error:
```
This site can’t be reached
host.robots.ox.ac.uk refused to connect.
Search Google for host robots 8080
ERR_CONNECTION_REFUSED
```

**Comment by qiuwch** [comment]
I can open http://host.robots.ox.ac.uk:8080, here is my screenshot.

![image](https://user-images.githubusercontent.com/1688418/28394252-921390e2-6cb9-11e7-9870-d73620adbf90.png)

**Comment by matthew-richard** [comment]
Last guess - Hang, how about this URL? There's no :8080, which seems to 
be what you're having trouble connecting to:

http://host.robots.ox.ac.uk/eval/downloads/VOC2010test.tar/

**Comment by zhanghang1989** [comment]
The isp seems to block the website. It is working now. Thank you very much!
