### ISSUE TITLE
Error using API

### ISSUE THREAD

**Issue by zhanghang1989** [ccvl/detail-api#3]
`Detail('trainval_merged.json', imgDir, phase)` got
```bash
  File "/home/hangzhang/anaconda3/lib/python3.6/site-packages/detail/__init__.py", line 81, in __init__
    self.__createIndex()
  File "/home/hangzhang/anaconda3/lib/python3.6/site-packages/detail/__init__.py", line 101, in __createIndex
    for skeleton in self.data['annos_joints']:          # many per image
KeyError: 'annos_joints'
```

**Comment by dsitnik** [comment]
Same problem with:
```
annFile='../../../trainval_parts.json' # annotations
imgDir='../../../VOCdevkit/VOC2010/JPEGImages' # jpeg images
phase='trainval'
details = Detail(annFile, imgDir, phase)

print('\n***info***')
details.info()
```

I got error:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-5-612c0f177226> in <module>()
----> 1 details = Detail(annFile, imgDir, phase)
      2 
      3 print('\n***info***')
      4 details.info()

/usr/lib64/python3.6/site-packages/detail/__init__.py in __init__(self, annotation_file, image_folder, phase)
     79 
     80         self.waiting = False
---> 81         self.__createIndex()
     82 
     83     def __createIndex(self):

/usr/lib64/python3.6/site-packages/detail/__init__.py in __createIndex(self)
     93         for img in self.data['images']:
     94             self.imgs[img['image_id']] = img
---> 95         for segm in self.data['annos_segmentation']:        # many per image
     96             self.segmentations[segm['id']] = segm
     97         for occl in self.data['annos_occlusion']:           # one per image

KeyError: 'annos_segmentation'
```

**Comment by zhanghang1989** [comment]
@dsitnik  comment out the following lines solves the problem temporarily, if you are not using joints annotations
https://github.com/ccvl/detail-api/blob/master/PythonAPI/detail/__init__.py#L101-L104

**Comment by dsitnik** [comment]
@zhanghang1989 That worked for now, thanks :+1:

**Comment by dsitnik** [comment]
@zhanghang1989 That worked for now, thanks :+1:

**Comment by matthew-richard** [comment]
Finally responding to you...thanks for persisting in my absence. I was between jobs and let this fall by the wayside. 

Download the new dataset with `python download.py trainval_withkeypoints <dir>`. The error was from the upgraded Detail API wanting the new dataset.

Development is resuming for the challenge. The [CVPR website](https://sites.google.com/view/pasd/dataset) is quite outdated as we migrate to a website that isn't tied to CVPR. I'll be providing support via this repo for now and will eventually bring in a student with more time on their hands to provide additional support.

Fire away with questions/issues. I'm primarily focused on getting the evaluation server setup, but updates to the Detail API for evaluating algorithm performance are on the way as well.

As always, I'm also monitoring pascalindetail@gmail.com.

**Comment by zhanghang1989** [comment]
Hi @mricha56 , is there any update about the challenge?
